const districts = [
  // Dhaka Division
  { name: 'Dhaka', name_bn: 'ঢাকা', divisionIndex: 0, code: '13' },
  { name: 'Gazipur', name_bn: 'গাজীপুর', divisionIndex: 0, code: '33' },
  { name: 'Narayanganj', name_bn: 'নারায়ণগঞ্জ', divisionIndex: 0, code: '67' },
  { name: 'Narsingdi', name_bn: 'নরসিংদী', divisionIndex: 0, code: '68' },
  { name: 'Manikganj', name_bn: 'মানিকগঞ্জ', divisionIndex: 0, code: '54' },
  { name: 'Munshiganj', name_bn: 'মুন্সীগঞ্জ', divisionIndex: 0, code: '59' },
  { name: 'Tangail', name_bn: 'টাঙ্গাইল', divisionIndex: 0, code: '93' },
  { name: 'Faridpur', name_bn: 'ফরিদপুর', divisionIndex: 0, code: '29' },
  { name: 'Rajbari', name_bn: 'রাজবাড়ী', divisionIndex: 0, code: '82' },
  { name: 'Gopalganj', name_bn: 'গোপালগঞ্জ', divisionIndex: 0, code: '35' },
  { name: 'Madaripur', name_bn: 'মাদারীপুর', divisionIndex: 0, code: '54' },
  { name: 'Shariatpur', name_bn: 'শরীয়তপুর', divisionIndex: 0, code: '86' },
  { name: 'Kishoreganj', name_bn: 'কিশোরগঞ্জ', divisionIndex: 0, code: '48' },
  // Chattogram Division
  { name: 'Chattogram', name_bn: 'চট্টগ্রাম', divisionIndex: 1, code: '15' },
  { name: "Cox's Bazar", name_bn: 'কক্সবাজার', divisionIndex: 1, code: '22' },
  { name: 'Bandarban', name_bn: 'বান্দরবান', divisionIndex: 1, code: '03' },
  { name: 'Rangamati', name_bn: 'রাঙ্গামাটি', divisionIndex: 1, code: '84' },
  { name: 'Khagrachari', name_bn: 'খাগড়াছড়ি', divisionIndex: 1, code: '47' },
  { name: 'Cumilla', name_bn: 'কুমিল্লা', divisionIndex: 1, code: '19' },
  { name: 'Feni', name_bn: 'ফেনী', divisionIndex: 1, code: '30' },
  { name: 'Noakhali', name_bn: 'নোয়াখালী', divisionIndex: 1, code: '75' },
  { name: 'Lakshmipur', name_bn: 'লক্ষ্মীপুর', divisionIndex: 1, code: '51' },
  { name: 'Chandpur', name_bn: 'চাঁদপুর', divisionIndex: 1, code: '09' },
  { name: 'Brahmanbaria', name_bn: 'ব্রাহ্মণবাড়িয়া', divisionIndex: 1, code: '12' },
  // Rajshahi Division
  { name: 'Rajshahi', name_bn: 'রাজশাহী', divisionIndex: 2, code: '81' },
  { name: 'Pabna', name_bn: 'পাবনা', divisionIndex: 2, code: '76' },
  { name: 'Natore', name_bn: 'নাটোর', divisionIndex: 2, code: '69' },
  { name: 'Sirajganj', name_bn: 'সিরাজগঞ্জ', divisionIndex: 2, code: '88' },
  { name: 'Bogura', name_bn: 'বগুড়া', divisionIndex: 2, code: '10' },
  { name: 'Joypurhat', name_bn: 'জয়পুরহাট', divisionIndex: 2, code: '38' },
  { name: 'Chapainawabganj', name_bn: 'চাঁপাইনবাবগঞ্জ', divisionIndex: 2, code: '70' },
  { name: 'Naogaon', name_bn: 'নওগাঁ', divisionIndex: 2, code: '65' },
  // Khulna Division
  { name: 'Khulna', name_bn: 'খুলনা', divisionIndex: 3, code: '47' },
  { name: 'Bagerhat', name_bn: 'বাগেরহাট', divisionIndex: 3, code: '01' },
  { name: 'Satkhira', name_bn: 'সাতক্ষীরা', divisionIndex: 3, code: '87' },
  { name: 'Jashore', name_bn: 'যশোর', divisionIndex: 3, code: '39' },
  { name: 'Jhenaidah', name_bn: 'ঝিনাইদহ', divisionIndex: 3, code: '44' },
  { name: 'Magura', name_bn: 'মাগুরা', divisionIndex: 3, code: '53' },
  { name: 'Narail', name_bn: 'নড়াইল', divisionIndex: 3, code: '65' },
  { name: 'Chuadanga', name_bn: 'চুয়াডাঙ্গা', divisionIndex: 3, code: '18' },
  { name: 'Kushtia', name_bn: 'কুষ্টিয়া', divisionIndex: 3, code: '50' },
  { name: 'Meherpur', name_bn: 'মেহেরপুর', divisionIndex: 3, code: '57' },
  // Barishal Division
  { name: 'Barishal', name_bn: 'বরিশাল', divisionIndex: 4, code: '06' },
  { name: 'Bhola', name_bn: 'ভোলা', divisionIndex: 4, code: '09' },
  { name: 'Patuakhali', name_bn: 'পটুয়াখালী', divisionIndex: 4, code: '78' },
  { name: 'Barguna', name_bn: 'বরগুনা', divisionIndex: 4, code: '04' },
  { name: 'Pirojpur', name_bn: 'পিরোজপুর', divisionIndex: 4, code: '79' },
  { name: 'Jhalokathi', name_bn: 'ঝালকাঠি', divisionIndex: 4, code: '42' },
  // Sylhet Division
  { name: 'Sylhet', name_bn: 'সিলেট', divisionIndex: 5, code: '91' },
  { name: 'Moulvibazar', name_bn: 'মৌলভীবাজার', divisionIndex: 5, code: '58' },
  { name: 'Habiganj', name_bn: 'হবিগঞ্জ', divisionIndex: 5, code: '36' },
  { name: 'Sunamganj', name_bn: 'সুনামগঞ্জ', divisionIndex: 5, code: '90' },
  // Rangpur Division
  { name: 'Rangpur', name_bn: 'রংপুর', divisionIndex: 6, code: '85' },
  { name: 'Dinajpur', name_bn: 'দিনাজপুর', divisionIndex: 6, code: '27' },
  { name: 'Panchagarh', name_bn: 'পঞ্চগড়', divisionIndex: 6, code: '77' },
  { name: 'Thakurgaon', name_bn: 'ঠাকুরগাঁও', divisionIndex: 6, code: '94' },
  { name: 'Nilphamari', name_bn: 'নীলফামারী', divisionIndex: 6, code: '73' },
  { name: 'Lalmonirhat', name_bn: 'লালমনিরহাট', divisionIndex: 6, code: '52' },
  { name: 'Kurigram', name_bn: 'কুড়িগ্রাম', divisionIndex: 6, code: '49' },
  { name: 'Gaibandha', name_bn: 'গাইবান্ধা', divisionIndex: 6, code: '32' },
  // Mymensingh Division
  { name: 'Mymensingh', name_bn: 'ময়মনসিংহ', divisionIndex: 7, code: '61' },
  { name: 'Jamalpur', name_bn: 'জামালপুর', divisionIndex: 7, code: '39' },
  { name: 'Sherpur', name_bn: 'শেরপুর', divisionIndex: 7, code: '89' },
  { name: 'Netrokona', name_bn: 'নেত্রকোণা', divisionIndex: 7, code: '72' },
];

module.exports = districts;
